name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
          
    - name: Install dependencies
      run: make buildenv
      
    - name: Make
      run: make
      
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Release ${{ github.ref }}
        tag_name: ${{ github.ref }}
        body: |
            Changes in this Release
      env:  
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/python-socks5-server_0.0.1_amd64.deb
        asset_name: python-socks5-server_0.0.1_amd64.deb
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
        
    
    
      
